In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df =pd.read_csv("Patient_Data.csv" )

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
df = df.drop(columns = ["ReceptionistID", "CheckInTime"])
df= df[ ["PatientID", "Department", "Doctor", "BillAmount"] ]
df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [5]:
df =df.drop_duplicates(subset=["PatientID"])
df = df.reset_index(drop=True)
df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [6]:
df.head( 3 )

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0

In [7]:
avg = df["BillAmount"].mean()
df["BillAmount"] = df["BillAmount"].fillna(avg)
df

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333

In [8]:
dept = df.groupby("Department")["BillAmount"].sum()
dept = dept.reset_index()
dept

    Department    BillAmount
0   Cardiology  11200.000000
1  Dermatology   6233.333333
2    Neurology   6233.333333
3  Orthopedics   7500.000000

In [9]:
bill =pd.read_csv( "Billing_Data.csv")
m = pd.merge(df, bill, on="PatientID" )
m

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000

In [10]:
new_pts = pd.DataFrame({
    "PatientID": [106, 107],
    "Department": ["Cardiology", "Neurology"],
    "Doctor": ["Dr. Smith", "Dr. John"],
    "BillAmount": [4500.0, 5500.0]
})
df_row = pd.concat( [df, new_pts], axis=0 )
df_row = df_row.reset_index(drop=True)
df_row

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333
5        106   Cardiology  Dr. Smith  4500.000000
6        107    Neurology   Dr. John  5500.000000

In [11]:
new_cols = bill[["InsuranceCovered", "FinalAmount"]]
df_col = pd.concat([df, new_cols], axis= 1)
df_col

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Neurology,Dr. John,6233.333333,1500,3500
2,103,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Dermatology,Dr. Rose,6233.333333,1000,4000